### PR TITLE
bugfix STP shl/shr: bitwidth greater than 32bit

### PR DESCRIPTION
**Pull request by hriener**

### CODE REVIEW

**Comment by finnhaedicke** [comment]
I was just starting to check if this is a STP problem. Good you fixed it already. I will test it and then merge it.

**Comment by hriener** [comment]
Yearh :stuck_out_tongue_winking_eye: --- Recompiling and testing took a lot of time. Surprisingly, the old (32-bit) API version of STP's bvshl function passes our bvshl test case even if I increase the bit-width to 64-bit.

**Comment by finnhaedicke** [comment]
I just started the test run. including full bootstrap build and test. Lets see how much `ccache` can help there.

**Comment by hriener** [comment]
Me, too. Hopefully we don't use the same machine :smile:

**Comment by finnhaedicke** [comment]
Ok, done. It took 15 minutes... 
I get this the following 7 direct_STP related failures:

```
    1590 - direct_STP/QF_BV/bvsrem_t (Failed)
    1615 - direct_STP/QF_BV/bvshl_all (Failed)
    1617 - direct_STP/QF_BV/bvshr_t (Failed)
    1618 - direct_STP/QF_BV/bvashr_t (Failed)
    1628 - direct_STP/QF_BV/constant_69bit (Failed)
    1633 - direct_STP/cardinality_t/test_bdd_cardinality_with_bv (Timeout)
    1634 - direct_STP/cardinality_t/test_adder_cardinality_with_bv (Timeout)
```

In the previous development version of metaSMT only 6 failed:

```
    1590 - direct_STP/QF_BV/bvsrem_t (Failed)
    1615 - direct_STP/QF_BV/bvshl_all (Timeout)
    1618 - direct_STP/QF_BV/bvashr_t (Failed)
    1628 - direct_STP/QF_BV/constant_69bit (Failed)
    1633 - direct_STP/cardinality_t/test_bdd_cardinality_with_bv (Timeout)
    1634 - direct_STP/cardinality_t/test_adder_cardinality_with_bv (Timeout)
```

3 are related to shifting:
- `direct_STP/QF_BV/bvshl_al` went from timeout to fail
- `direct_STP/QF_BV/bvshr_t` now fails
- `direct_STP/QF_BV/bvashr_t` still fails

Do you also see these fails?

## bvashr_t

```
Running 1 test case...

unknown location(0): fatal error in "bvashr_t": signal: SIGABRT (application abort requested)
../tests/test_QF_BV.cpp(1686): last checkpoint
Fatal Error: GetBVConst: non bitvector-constant: 

2:FALSE
0
direct_STP: /home/jenkins/workspace/program-metaSMT-pr/deps/build/stp-git/lib/AST/ASTmisc.cpp:258: void stp::FatalError(const char*, const stp::ASTNode&, int): Assertion `false' failed.

*** 1 failure detected in test suite "direct_STP"
```

## bvshr_t

```
Running 1 test case...
../tests/test_QF_BV.cpp(1676): fatal error in "bvshr_t": critical check solve(ctx) failed

*** 1 failure detected in test suite "direct_STP"
```

## bvshl_all

```
Running 1 test case...
../tests/test_QF_BV.cpp(1638): fatal error in "bvshl_all": critical check shifted == zd failed [1 != 0]

*** 1 failure detected in test suite "graph_STP"
```

**Comment by hriener** [comment]
Patch is on the way. (The test case bvshl_all seems to take a while ...)

**Comment by finnhaedicke** [comment]
Thats why I test with a timeout of 5 seconds :clock1:

**Comment by hriener** [comment]
Please, try again.

**Comment by finnhaedicke** [comment]
Fixed. Feel free to merge it.

```
    1590 - direct_STP/QF_BV/bvsrem_t (Failed)
    1615 - direct_STP/QF_BV/bvshl_all (Timeout)
    1628 - direct_STP/QF_BV/constant_69bit (Failed)
    1633 - direct_STP/cardinality_t/test_bdd_cardinality_with_bv (Timeout)
    1634 - direct_STP/cardinality_t/test_adder_cardinality_with_bv (Timeout)
```

**Pull request merged**
