### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by keszocze**
These commits address issues #11 and #16. Issue #16 will be closed while issue #11 still
has some open questions left.

### CODE REVIEW

**Comment by finnhaedicke** [comment]
+1

**Comment by finnhaedicke** [comment]
@hriener: are the typos fixed now?

**Comment by keszocze** [comment]
Yes see commit f3e09e8

**Comment by finnhaedicke** [comment]
I have seen It, I would like to hear hriener comment on it. From my side its good to go.
:+1:

**Comment by hriener** [comment]
I read it and like it :+1:
@keszocze: Many thanks for improving the README so careful.
Minor comments: There is a dot missing at the end of the paragraph. ;)

**Pull request merged**
